spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:shareline}
    username: ${POSTGRES_USER:shareline}
    password: ${POSTGRES_PASSWORD:shareline}

server:
  forward-headers-strategy: framework
  use-forward-headers: true

shareline:
  upload-dir: /app/uploads
  base-url: ${SHARELINE_BASE_URL:http://localhost:8080}

